doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/Users/Domain'
                prefix: 'App\Module\Users\Domain\User'
                alias: User
            Feed:
                is_bundle: false
                type: annotation # @todo migrate later to yml !!!
                dir: '%kernel.project_dir%/src/Module/Feed/Domain'
                prefix: 'App\Module\Feed\Domain\Feed'
                alias: Feed
