security:
  encoders:
    App\Module\Users\Domain\User:
      algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    users:
      entity:
        # the class of the entity that represents users
        class: App\Module\Users\Domain\User
        property: 'email'

  firewalls:
    guest:
      pattern: ^/(api/register|api/verify|api/logout)
      anonymous: ~

    main:
      pattern: ^/api
      json_login:
        check_path: /api/login
      logout:
        path: /api/logout
