version: '2'

services:
  php:
    build:
      context: docker/php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    env_file:
      - .env
    volumes:
      - ./www:/var/www
      - ./docker/logs/symfony:/var/www/symfony/app/logs

  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx

  db:
    image: mysql
    volumes:
      - "./docker/.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}