frontend.index:
    methods: GET
    path: /
    controller: \App\Controller\FrontEndController::index

auth.login:
    methods: POST
    path: /api/login
    controller: \App\Controller\AuthController::login

auth.logout:
    methods: POST
    path: /api/logout
    controller: \App\Controller\AuthController::logout

auth.register:
    methods: POST
    path: /api/register
    controller: \App\Controller\AuthController::register

auth.verify:
    methods: HEAD
    path: /api/verify
    controller: \App\Controller\AuthController::verify


feed.list:
    methods: GET
    path: /api/feed
    controller: \App\Controller\FeedController::feedList

feed.full:
    methods: GET
    path: /api/feed/{id}
    controller: \App\Controller\FeedController::feed

feed.tags:
    methods: GET
    path: /api/feed/tags
    controller: \App\Controller\FeedController::feedTags
